const translations = {
  en: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "How do you use this playground?",
    intro: "We're gathering community input to help shape the future of General Hart Playground.",
    share: "Share",
    vote: "Vote",
    meta: "Open to all • Any language • No account needed",
    inspirationPrompt: "Want to see how other playgrounds are being reimagined around the world?",
    inspirationPromptVote: "Want to see what's possible for this space?",
    designReferenceBtn: "Explore design references →",
    
    // Share flow
    progressStep: "Step",
    progressOf: "of",
    shareStep1Title: "Take or upload a photo",
    shareStep1Helper: "This can be anything — play, rest, gathering, waiting, passing through.",
    uploadPhoto: "Upload photo",
    skipStep: "Skip this step",
    privacyNote: "Faces can be blurred. Photos are used only for community planning.",
    shareStep2Title: "What's happening here?",
    shareStep2Helper: "A sentence or two is enough. Write in any language.",
    textareaPlaceholder: "My kids wait here after school because there's shade.",
    submit: "Submit",
    shareStep3Title: "A little context helps",
    shareStep3Helper: "These patterns help us understand how the playground is used.",
    timeLabel: "Time of day",
    morning: "Morning",
    afternoon: "Afternoon",
    evening: "Evening",
    finish: "Finish",
    shareStep4Title: "Thank you for sharing",
    shareStep4Text: "Your perspective helps guide decisions about this space.",
    updatesLabel: "Want updates on workshops and next steps?",
    emailPlaceholder: "your@email.com (optional)",
    done: "Done",
    
    // Vote flow
    voteStep1Title: "What would most improve this playground?",
    voteInstructions: "Pick two or more",
    voteOptionShade: "More shade",
    voteOptionSeating: "More seating",
    voteOptionEquipment: "Better play equipment",
    voteOptionGathering: "A space for gathering",
    voteOptionOther: "Other",
    voteOtherPlaceholder: "Tell us what would help...",
    voteStep2Title: "Thanks — your input has been counted",
    voteStep2Helper: "Want to share how you use the playground?",
    getUpdates: "Get project updates",
    
    // Alerts
    alertDescription: "Please add a description before continuing.",
    alertVote: "Please select at least two options.",
    alertVoteOtherEmpty: "Please describe what 'Other' means to you."
  },
  
  es: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "¿Cómo usa este patio?",
    intro: "Estamos reuniendo opiniones de la comunidad para dar forma al futuro del parque General Hart.",
    share: "Compartir",
    vote: "Votar",
    meta: "Abierto a todos • Cualquier idioma • No se necesita cuenta",
    inspirationPrompt: "¿Quiere ver cómo se están reimaginando otros parques infantiles en todo el mundo?",
    inspirationPromptVote: "¿Quiere ver qué es posible para este espacio?",
    designReferenceBtn: "Explorar referencias de diseño →",
    
    // Share flow
    progressStep: "Paso",
    progressOf: "de",
    shareStep1Title: "Tome o suba una foto",
    shareStep1Helper: "Esto puede ser cualquier cosa: jugar, descansar, reunirse, esperar, pasar.",
    uploadPhoto: "Subir foto",
    skipStep: "Saltar este paso",
    privacyNote: "Los rostros pueden difuminarse. Las fotos se usan solo para planificación comunitaria.",
    shareStep2Title: "¿Qué está pasando aquí?",
    shareStep2Helper: "Una o dos oraciones son suficientes. Escriba en cualquier idioma.",
    textareaPlaceholder: "Mis hijos esperan aquí después de la escuela porque hay sombra.",
    submit: "Enviar",
    shareStep3Title: "Un poco de contexto ayuda",
    shareStep3Helper: "Estos patrones nos ayudan a entender cómo se usa el parque.",
    timeLabel: "Hora del día",
    morning: "Mañana",
    afternoon: "Tarde",
    evening: "Noche",
    finish: "Terminar",
    shareStep4Title: "Gracias por compartir",
    shareStep4Text: "Su perspectiva ayuda a guiar las decisiones sobre este espacio.",
    updatesLabel: "¿Quiere recibir actualizaciones sobre talleres y próximos pasos?",
    emailPlaceholder: "su@email.com (opcional)",
    done: "Hecho",
    
    // Vote flow
    voteStep1Title: "¿Qué mejoraría más este parque?",
    voteInstructions: "Elija dos o más",
    voteOptionShade: "Más sombra",
    voteOptionSeating: "Más asientos",
    voteOptionEquipment: "Mejor equipo de juego",
    voteOptionGathering: "Un espacio para reunirse",
    voteOptionOther: "Otro",
    voteOtherPlaceholder: "Díganos qué ayudaría...",
    voteStep2Title: "Gracias — su opinión ha sido contada",
    voteStep2Helper: "¿Quiere compartir cómo usa el parque?",
    getUpdates: "Recibir actualizaciones del proyecto",
    
    // Alerts
    alertDescription: "Por favor agregue una descripción antes de continuar.",
    alertVote: "Por favor seleccione al menos dos opciones.",
    alertVoteOtherEmpty: "Por favor describa qué significa 'Otro' para usted."
  },
  
  tl: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "Paano mo ginagamit ang playground na ito?",
    intro: "Nangongolekta kami ng input mula sa komunidad upang makagawa ng kinabukasan ng General Hart Playground.",
    share: "Ibahagi",
    vote: "Bumoto",
    meta: "Bukas sa lahat • Anumang wika • Walang kailangang account",
    inspirationPrompt: "Gusto mo bang makita kung paano muling iniimagine ang ibang playground sa buong mundo?",
    inspirationPromptVote: "Gusto mo bang makita kung ano ang posible para sa espasyong ito?",
    designReferenceBtn: "Tuklasin ang mga sanggunian ng disenyo →",
    
    // Share flow
    progressStep: "Hakbang",
    progressOf: "ng",
    shareStep1Title: "Kumuha o mag-upload ng larawan",
    shareStep1Helper: "Ito ay maaaring kahit ano — paglalaro, pahinga, pagtitipon, paghihintay, pagdaan.",
    uploadPhoto: "Mag-upload ng larawan",
    skipStep: "Laktawan ang hakbang na ito",
    privacyNote: "Maaaring labo ang mga mukha. Ang mga larawan ay ginagamit lamang para sa pagpaplano ng komunidad.",
    shareStep2Title: "Ano ang nangyayari dito?",
    shareStep2Helper: "Isa o dalawang pangungusap ay sapat. Magsulat sa anumang wika.",
    textareaPlaceholder: "Ang aking mga anak ay naghihintay dito pagkatapos ng klase dahil may lilim.",
    submit: "Isumite",
    shareStep3Title: "Ang kaunting konteksto ay nakakatulong",
    shareStep3Helper: "Ang mga pattern na ito ay tumutulong sa amin na maunawaan kung paano ginagamit ang playground.",
    timeLabel: "Oras ng araw",
    morning: "Umaga",
    afternoon: "Hapon",
    evening: "Gabi",
    finish: "Tapusin",
    shareStep4Title: "Salamat sa pagbahagi",
    shareStep4Text: "Ang iyong pananaw ay tumutulong sa paggabay sa mga desisyon tungkol sa espasyong ito.",
    updatesLabel: "Gusto mo bang makatanggap ng mga update sa mga workshop at susunod na hakbang?",
    emailPlaceholder: "ang-iyong@email.com (opsyonal)",
    done: "Tapos na",
    
    // Vote flow
    voteStep1Title: "Ano ang pinakapagpapabuti sa playground na ito?",
    voteInstructions: "Pumili ng dalawa o higit pa",
    voteOptionShade: "Mas maraming lilim",
    voteOptionSeating: "Mas maraming upuan",
    voteOptionEquipment: "Mas magandang kagamitan sa paglalaro",
    voteOptionGathering: "Isang espasyo para sa pagtitipon",
    voteOptionOther: "Iba pa",
    voteOtherPlaceholder: "Sabihin sa amin kung ano ang makakatulong...",
    voteStep2Title: "Salamat — ang iyong input ay nabilang na",
    voteStep2Helper: "Gusto mo bang ibahagi kung paano mo ginagamit ang playground?",
    getUpdates: "Makatanggap ng mga update sa proyekto",
    
    // Alerts
    alertDescription: "Mangyaring magdagdag ng paglalarawan bago magpatuloy.",
    alertVote: "Mangyaring pumili ng hindi bababa sa dalawang opsyon.",
    alertVoteOtherEmpty: "Mangyaring ilarawan kung ano ang ibig sabihin ng 'Iba pa' para sa iyo."
  },
  
  bn: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "আপনি এই খেলার মাঠটি কীভাবে ব্যবহার করেন?",
    intro: "আমরা জেনারেল হার্ট খেলার মাঠের ভবিষ্যৎ গঠনে সাহায্য করতে সম্প্রদায়ের ইনপুট সংগ্রহ করছি।",
    share: "শেয়ার করুন",
    vote: "ভোট দিন",
    meta: "সবার জন্য উন্মুক্ত • যেকোনো ভাষা • কোনো অ্যাকাউন্ট প্রয়োজন নেই",
    inspirationPrompt: "সারা বিশ্বে অন্যান্য খেলার মাঠ কীভাবে পুনর্কল্পনা করা হচ্ছে তা দেখতে চান?",
    inspirationPromptVote: "এই স্থানের জন্য কী সম্ভব তা দেখতে চান?",
    designReferenceBtn: "ডিজাইন রেফারেন্স অন্বেষণ করুন →",
    
    // Share flow
    progressStep: "ধাপ",
    progressOf: "এর",
    shareStep1Title: "একটি ছবি তুলুন বা আপলোড করুন",
    shareStep1Helper: "এটি যেকোনো কিছু হতে পারে — খেলা, বিশ্রাম, জমায়েত, অপেক্ষা, পাশ দিয়ে যাওয়া।",
    uploadPhoto: "ছবি আপলোড করুন",
    skipStep: "এই ধাপটি এড়িয়ে যান",
    privacyNote: "মুখ ঝাপসা করা যেতে পারে। ছবিগুলি শুধুমাত্র সম্প্রদায় পরিকল্পনার জন্য ব্যবহৃত হয়।",
    shareStep2Title: "এখানে কী ঘটছে?",
    shareStep2Helper: "একটি বা দুটি বাক্য যথেষ্ট। যেকোনো ভাষায় লিখুন।",
    textareaPlaceholder: "আমার বাচ্চারা স্কুলের পরে এখানে অপেক্ষা করে কারণ এখানে ছায়া আছে।",
    submit: "জমা দিন",
    shareStep3Title: "একটু প্রসঙ্গ সাহায্য করে",
    shareStep3Helper: "এই প্যাটার্নগুলি আমাদের বুঝতে সাহায্য করে খেলার মাঠটি কীভাবে ব্যবহৃত হয়।",
    timeLabel: "দিনের সময়",
    morning: "সকাল",
    afternoon: "বিকেল",
    evening: "সন্ধ্যা",
    finish: "শেষ করুন",
    shareStep4Title: "শেয়ার করার জন্য ধন্যবাদ",
    shareStep4Text: "আপনার দৃষ্টিভঙ্গি এই স্থান সম্পর্কে সিদ্ধান্ত গাইড করতে সাহায্য করে।",
    updatesLabel: "কর্মশালা এবং পরবর্তী পদক্ষেপের আপডেট চান?",
    emailPlaceholder: "আপনার@email.com (ঐচ্ছিক)",
    done: "সম্পন্ন",
    
    // Vote flow
    voteStep1Title: "এই খেলার মাঠের সবচেয়ে উন্নতি কী হবে?",
    voteInstructions: "দুটি বা তার বেশি বেছে নিন",
    voteOptionShade: "আরও ছায়া",
    voteOptionSeating: "আরও বসার জায়গা",
    voteOptionEquipment: "আরও ভাল খেলার সরঞ্জাম",
    voteOptionGathering: "জমায়েতের জন্য একটি স্থান",
    voteOptionOther: "অন্যান্য",
    voteOtherPlaceholder: "আমাদের বলুন কী সাহায্য করবে...",
    voteStep2Title: "ধন্যবাদ — আপনার ইনপুট গণনা করা হয়েছে",
    voteStep2Helper: "আপনি কীভাবে খেলার মাঠটি ব্যবহার করেন তা শেয়ার করতে চান?",
    getUpdates: "প্রকল্পের আপডেট পান",
    
    // Alerts
    alertDescription: "অব্যাহত রাখার আগে একটি বর্ণনা যোগ করুন।",
    alertVote: "অন্তত দুটি বিকল্প নির্বাচন করুন।",
    alertVoteOtherEmpty: "অনুগ্রহ করে 'অন্যান্য' এর অর্থ বর্ণনা করুন।"
  },
  
  ne: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "तपाईं यो खेल मैदान कसरी प्रयोग गर्नुहुन्छ?",
    intro: "हामी जनरल हार्ट खेल मैदानको भविष्य आकार दिन मद्दत गर्न समुदायको इनपुट सङ्कलन गर्दैछौं।",
    share: "साझा गर्नुहोस्",
    vote: "मतदान गर्नुहोस्",
    meta: "सबैका लागि खुला • कुनै पनि भाषा • कुनै खाता आवश्यक छैन",
    inspirationPrompt: "विश्वभर अन्य खेल मैदानहरू कसरी पुन: कल्पना गरिँदैछ हेर्न चाहनुहुन्छ?",
    inspirationPromptVote: "यो स्थानको लागि के सम्भव छ हेर्न चाहनुहुन्छ?",
    designReferenceBtn: "डिजाइन सन्दर्भहरू अन्वेषण गर्नुहोस् →",
    
    // Share flow
    progressStep: "चरण",
    progressOf: "को",
    shareStep1Title: "तस्बिर खिच्नुहोस् वा अपलोड गर्नुहोस्",
    shareStep1Helper: "यो जे पनि हुन सक्छ — खेल्ने, आराम गर्ने, भेला हुने, पर्खने, पार गर्ने।",
    uploadPhoto: "तस्बिर अपलोड गर्नुहोस्",
    skipStep: "यो चरण छोड्नुहोस्",
    privacyNote: "अनुहारहरू धमिलो पार्न सकिन्छ। तस्बिरहरू केवल समुदाय योजनाको लागि प्रयोग गरिन्छ।",
    shareStep2Title: "यहाँ के भइरहेको छ?",
    shareStep2Helper: "एक वा दुई वाक्य पर्याप्त छ। कुनै पनि भाषामा लेख्नुहोस्।",
    textareaPlaceholder: "मेरा बच्चाहरू स्कूल पछि यहाँ पर्खन्छन् किनभने यहाँ छाया छ।",
    submit: "पेश गर्नुहोस्",
    shareStep3Title: "थोरै सन्दर्भले मद्दत गर्छ",
    shareStep3Helper: "यी ढाँचाहरूले हामीलाई खेल मैदान कसरी प्रयोग गरिन्छ बुझ्न मद्दत गर्छ।",
    timeLabel: "दिनको समय",
    morning: "बिहान",
    afternoon: "दिउँसो",
    evening: "साँझ",
    finish: "समाप्त गर्नुहोस्",
    shareStep4Title: "साझा गर्नुभएकोमा धन्यवाद",
    shareStep4Text: "तपाईंको दृष्टिकोणले यो स्थानको बारेमा निर्णयहरू मार्गदर्शन गर्न मद्दत गर्छ।",
    updatesLabel: "कार्यशालाहरू र अर्को चरणहरूमा अद्यावधिकहरू चाहनुहुन्छ?",
    emailPlaceholder: "तपाईंको@email.com (वैकल्पिक)",
    done: "सम्पन्न",
    
    // Vote flow
    voteStep1Title: "यो खेल मैदानमा के सबैभन्दा राम्रो सुधार हुनेछ?",
    voteInstructions: "दुई वा बढी छान्नुहोस्",
    voteOptionShade: "थप छाया",
    voteOptionSeating: "थप बस्ने ठाउँ",
    voteOptionEquipment: "राम्रो खेल उपकरण",
    voteOptionGathering: "भेला हुने ठाउँ",
    voteOptionOther: "अन्य",
    voteOtherPlaceholder: "हामीलाई के मद्दत गर्छ भन्नुहोस्...",
    voteStep2Title: "धन्यवाद — तपाईंको इनपुट गणना गरिएको छ",
    voteStep2Helper: "तपाईं खेल मैदान कसरी प्रयोग गर्नुहुन्छ साझा गर्न चाहनुहुन्छ?",
    getUpdates: "परियोजना अद्यावधिकहरू प्राप्त गर्नुहोस्",
    
    // Alerts
    alertDescription: "कृपया जारी राख्नु अघि विवरण थप्नुहोस्।",
    alertVote: "कृपया कम्तिमा दुई विकल्पहरू चयन गर्नुहोस्।",
    alertVoteOtherEmpty: "कृपया 'अन्य' को अर्थ वर्णन गर्नुहोस्।"
  },
  
  zh: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "您如何使用这个游乐场？",
    intro: "我们正在收集社区意见，以帮助塑造哈特将军游乐场的未来。",
    share: "分享",
    vote: "投票",
    meta: "向所有人开放 • 任何语言 • 无需账户",
    inspirationPrompt: "想看看世界各地的其他游乐场是如何重新构想的吗？",
    inspirationPromptVote: "想看看这个空间有什么可能吗？",
    designReferenceBtn: "探索设计参考 →",
    
    // Share flow
    progressStep: "步骤",
    progressOf: "共",
    shareStep1Title: "拍摄或上传照片",
    shareStep1Helper: "这可以是任何东西——玩耍、休息、聚会、等待、路过。",
    uploadPhoto: "上传照片",
    skipStep: "跳过此步骤",
    privacyNote: "面部可以模糊。照片仅用于社区规划。",
    shareStep2Title: "这里发生了什么？",
    shareStep2Helper: "一两句话就够了。用任何语言书写。",
    textareaPlaceholder: "我的孩子们放学后在这里等待，因为这里有阴凉。",
    submit: "提交",
    shareStep3Title: "一点背景有帮助",
    shareStep3Helper: "这些模式帮助我们了解游乐场是如何使用的。",
    timeLabel: "一天中的时间",
    morning: "早上",
    afternoon: "下午",
    evening: "晚上",
    finish: "完成",
    shareStep4Title: "感谢分享",
    shareStep4Text: "您的观点有助于指导有关该空间的决策。",
    updatesLabel: "想要获取有关研讨会和下一步的更新吗？",
    emailPlaceholder: "您的@email.com（可选）",
    done: "完成",
    
    // Vote flow
    voteStep1Title: "什么最能改善这个游乐场？",
    voteInstructions: "选择两个或更多",
    voteOptionShade: "更多阴凉",
    voteOptionSeating: "更多座位",
    voteOptionEquipment: "更好的游乐设备",
    voteOptionGathering: "聚会空间",
    voteOptionOther: "其他",
    voteOtherPlaceholder: "告诉我们什么会有帮助...",
    voteStep2Title: "谢谢——您的意见已被计算",
    voteStep2Helper: "想分享您如何使用游乐场吗？",
    getUpdates: "获取项目更新",
    
    // Alerts
    alertDescription: "请在继续之前添加描述。",
    alertVote: "请至少选择两个选项。",
    alertVoteOtherEmpty: "请描述'其他'对您的意义。"
  },
  
  sa: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "भवन्तः एतत् क्रीडाक्षेत्रं कथं उपयुञ्जते?",
    intro: "वयं जनरल हार्ट क्रीडाक्षेत्रस्य भविष्यं आकारयितुं समुदायस्य निवेशं सङ्गृह्णीमः।",
    share: "साझं करोतु",
    vote: "मतं ददातु",
    meta: "सर्वेभ्यः मुक्तम् • कापि भाषा • लेखा न आवश्यकी",
    inspirationPrompt: "किं भवान् विश्वे अन्येषु क्रीडाक्षेत्रेषु कथं पुनः कल्पना क्रियते इति द्रष्टुम् इच्छति?",
    inspirationPromptVote: "किं एतस्मै स्थानाय किं सम्भवम् इति द्रष्टुम् इच्छति?",
    designReferenceBtn: "डिज़ाइन-सन्दर्भान् अन्वेषयतु →",
    
    // Share flow
    progressStep: "पदम्",
    progressOf: "इत्यस्य",
    shareStep1Title: "चित्रं गृह्णातु वा उत्तारयतु",
    shareStep1Helper: "एतत् किमपि भवितुम् अर्हति — क्रीडनम्, विश्रामः, समवायः, प्रतीक्षा, पारगमनम्।",
    uploadPhoto: "चित्रम् उत्तारयतु",
    skipStep: "एतत् पदं त्यजतु",
    privacyNote: "मुखानि अस्पष्टानि कर्तुं शक्यन्ते। चित्राणि केवलं समुदाय-योजनायै उपयुज्यन्ते।",
    shareStep2Title: "अत्र किं भवति?",
    shareStep2Helper: "एकं द्वौ वा वाक्यौ पर्याप्तौ। कस्यामपि भाषायां लिखतु।",
    textareaPlaceholder: "मम बालकाः विद्यालयात् अनन्तरं अत्र प्रतीक्षन्ते यतः अत्र छाया अस्ति।",
    submit: "समर्पयतु",
    shareStep3Title: "किञ्चित् सन्दर्भः साहाय्यं करोति",
    shareStep3Helper: "एताः प्रतिमानाः अस्मान् क्रीडाक्षेत्रं कथं उपयुज्यते इति बोधयितुं साहाय्यं कुर्वन्ति।",
    timeLabel: "दिवसस्य समयः",
    morning: "प्रातः",
    afternoon: "अपराह्णः",
    evening: "सायम्",
    finish: "समाप्नोतु",
    shareStep4Title: "साझं कृतस्य कृते धन्यवादः",
    shareStep4Text: "भवतः दृष्टिकोणः एतस्मिन् स्थाने विषये निर्णयान् मार्गदर्शयितुं साहाय्यं करोति।",
    updatesLabel: "कार्यशालासु अग्रिमपदेषु च नूतनीकरणानि इच्छति वा?",
    emailPlaceholder: "भवतः@email.com (वैकल्पिकम्)",
    done: "समाप्तम्",
    
    // Vote flow
    voteStep1Title: "किं एतस्य क्रीडाक्षेत्रस्य उत्तमं सुधारं करिष्यति?",
    voteInstructions: "द्वौ अधिकान् वा चिनोतु",
    voteOptionShade: "अधिकं छाया",
    voteOptionSeating: "अधिकं उपवेशनम्",
    voteOptionEquipment: "उत्तमं क्रीडोपकरणम्",
    voteOptionGathering: "समवायाय स्थानम्",
    voteOptionOther: "अन्यत्",
    voteOtherPlaceholder: "अस्मभ्यं वदतु किं साहाय्यं करिष्यति...",
    voteStep2Title: "धन्यवादः — भवतः निवेशः गणितः",
    voteStep2Helper: "भवान् क्रीडाक्षेत्रं कथं उपयुनक्ति इति साझं कर्तुम् इच्छति वा?",
    getUpdates: "परियोजना-नूतनीकरणानि प्राप्नोतु",
    
    // Alerts
    alertDescription: "कृपया आगे बढ़ने से पूर्वं विवरणं योजयतु।",
    alertVote: "कृपया न्यूनतमं द्वौ विकल्पौ चिनोतु।",
    alertVoteOtherEmpty: "कृपया 'अन्यत्' इत्यस्य अर्थं वर्णयतु।"
  }
};
