const translations = {
  en: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "HOW DO YOU USE THIS PLAYGROUND?",
    intro: "We're redesigning General Hart Playground with input from the community who actually uses it.",
    aboutLabel: "ABOUT THIS PROJECT",
    aboutText: "STREETOYSTER QUEENS is commissioning an artist to reimagine this playground based on how you use it.",
    aboutMeta: "Alex Tudela, Woodside native\n2026 David Prize applicant\nIn conversation with NYC Parks & Community Board 2",
    share: "Share",
    vote: "Vote",
    timelineLabel: "WHAT HAPPENS NEXT",
    timelineSteps: "→ Spring 2026: Community provides feedback\n→ Summer 2026: Artist reviews community input\n→ Fall 2026: Design concepts shared\n→ Spring 2027: Installation begins",
    followText: "Follow the process:",
    meta: "Open to all · Any language · No account needed",
    inspirationPrompt: "Want to see how other playgrounds are being reimagined around the world?",
    inspirationPromptVote: "Want to see what's possible for this space?",
    designReferenceBtn: "Explore design references →",
    
    // Share flow
    shareStep1Label: "SHARE A PHOTO",
    shareStep1Title: "SHOW US HOW YOU USE THIS SPACE",
    shareStep1Helper: "Playing, resting, gathering, waiting, passing through—it all matters.",
    uploadPhoto: "TAKE OR UPLOAD PHOTO",
    skipStep: "SKIP THIS STEP",
    privacyNote: "Faces can be blurred\nPhotos used only for design planning\nChildren's privacy protected",
    shareStep2Label: "ADD CONTEXT (OPTIONAL)",
    shareStep2Title: "WHAT'S HAPPENING?",
    shareStep2Helper: "A sentence or two is perfect. Write in any language.",
    textareaPlaceholder: "My kids wait here after school because there's shade.",
    continueBtn: "CONTINUE",
    shareStep3Label: "WHEN WAS THIS?",
    shareStep3Title: "TIME OF DAY",
    shareStep3Helper: "Helps us understand when the playground is most used.",
    morning: "Morning",
    afternoon: "Afternoon",
    evening: "Evening",
    finish: "FINISH",
    shareStep4Title: "THANK YOU",
    shareStep4Text: "Your input will help shape the artist's design.",
    updatesLabel: "GET PROJECT UPDATES",
    emailPlaceholder: "your@email.com (optional)",
    emailMeta: "3-4 emails total about design progress. No spam.",
    done: "DONE",
    
    // Vote flow
    voteStep1Label: "YOUR PRIORITIES",
    voteStep1Title: "WHAT SHOULD THE ARTIST PRIORITIZE?",
    voteInstructions: "Pick two or more things that matter to you.",
    voteOptionShade: "More shade for hot days",
    voteOptionSeating: "Seating for grandparents and caregivers",
    voteOptionAges: "Play that works for different ages together",
    voteOptionCultures: "Spaces that feel connected to our cultures",
    voteOptionMovement: "Creative movement (not just standard equipment)",
    voteOptionGathering: "Places to gather, not just play",
    voteOptionOther: "Other",
    voteOtherPlaceholder: "Tell us what...",
    submitBtn: "SUBMIT",
    voteStep2Title: "YOUR INPUT HAS BEEN COUNTED",
    voteStep2Text: "The artist will use these priorities to guide the design.",
    seeReferencesBtn: "SEE DESIGN REFERENCES →",
    shareActionLabel: "WANT TO SHARE HOW YOU USE THE PLAYGROUND?",
    shareActionBtn: "SHARE A PHOTO",
    
    // Alerts
    alertDescription: "Please add a description before continuing.",
    alertVote: "Please select at least two options.",
    alertVoteOtherEmpty: "Please describe what 'Other' means to you."
  },
  
  es: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "¿CÓMO USA ESTE PATIO?",
    intro: "Estamos rediseñando el parque General Hart con aportes de la comunidad que realmente lo usa.",
    aboutLabel: "SOBRE ESTE PROYECTO",
    aboutText: "STREETOYSTER QUEENS está comisionando a un artista para reimaginar este patio según cómo lo uses.",
    aboutMeta: "Alex Tudela, nativo de Woodside\nCandidato al Premio David 2026\nEn conversación con NYC Parks y Community Board 2",
    share: "Compartir",
    vote: "Votar",
    timelineLabel: "QUÉ SIGUE",
    timelineSteps: "→ Primavera 2026: La comunidad proporciona comentarios\n→ Verano 2026: El artista revisa los aportes\n→ Otoño 2026: Se comparten conceptos de diseño\n→ Primavera 2027: Comienza la instalación",
    followText: "Siga el proceso:",
    meta: "Abierto a todos · Cualquier idioma · No se necesita cuenta",
    inspirationPrompt: "¿Quiere ver cómo se están reimaginando otros parques infantiles en todo el mundo?",
    inspirationPromptVote: "¿Quiere ver qué es posible para este espacio?",
    designReferenceBtn: "Explorar referencias de diseño →",
    
    // Share flow
    shareStep1Label: "COMPARTIR UNA FOTO",
    shareStep1Title: "MUÉSTRANOS CÓMO USAS ESTE ESPACIO",
    shareStep1Helper: "Jugar, descansar, reunirse, esperar, pasar—todo importa.",
    uploadPhoto: "TOMAR O SUBIR FOTO",
    skipStep: "SALTAR ESTE PASO",
    privacyNote: "Los rostros pueden difuminarse\nFotos usadas solo para planificación de diseño\nPrivacidad de niños protegida",
    shareStep2Label: "AGREGAR CONTEXTO (OPCIONAL)",
    shareStep2Title: "¿QUÉ ESTÁ PASANDO?",
    shareStep2Helper: "Una o dos oraciones es perfecto. Escriba en cualquier idioma.",
    textareaPlaceholder: "Mis hijos esperan aquí después de la escuela porque hay sombra.",
    continueBtn: "CONTINUAR",
    shareStep3Label: "¿CUÁNDO FUE ESTO?",
    shareStep3Title: "HORA DEL DÍA",
    shareStep3Helper: "Nos ayuda a entender cuándo el parque es más usado.",
    morning: "Mañana",
    afternoon: "Tarde",
    evening: "Noche",
    finish: "TERMINAR",
    shareStep4Title: "GRACIAS",
    shareStep4Text: "Su aporte ayudará a dar forma al diseño del artista.",
    updatesLabel: "RECIBIR ACTUALIZACIONES DEL PROYECTO",
    emailPlaceholder: "su@email.com (opcional)",
    emailMeta: "3-4 correos en total sobre el progreso del diseño. Sin spam.",
    done: "HECHO",
    
    // Vote flow
    voteStep1Label: "SUS PRIORIDADES",
    voteStep1Title: "¿QUÉ DEBE PRIORIZAR EL ARTISTA?",
    voteInstructions: "Elija dos o más cosas que le importen.",
    voteOptionShade: "Más sombra para días calurosos",
    voteOptionSeating: "Asientos para abuelos y cuidadores",
    voteOptionAges: "Juego que funcione para diferentes edades juntas",
    voteOptionCultures: "Espacios que se sientan conectados a nuestras culturas",
    voteOptionMovement: "Movimiento creativo (no solo equipo estándar)",
    voteOptionGathering: "Lugares para reunirse, no solo jugar",
    voteOptionOther: "Otro",
    voteOtherPlaceholder: "Díganos qué...",
    submitBtn: "ENVIAR",
    voteStep2Title: "SU OPINIÓN HA SIDO CONTADA",
    voteStep2Text: "El artista usará estas prioridades para guiar el diseño.",
    seeReferencesBtn: "VER REFERENCIAS DE DISEÑO →",
    shareActionLabel: "¿QUIERE COMPARTIR CÓMO USA EL PARQUE?",
    shareActionBtn: "COMPARTIR UNA FOTO",
    
    // Alerts
    alertDescription: "Por favor agregue una descripción antes de continuar.",
    alertVote: "Por favor seleccione al menos dos opciones.",
    alertVoteOtherEmpty: "Por favor describa qué significa 'Otro' para usted."
  },
  
  tl: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "PAANO MO GINAGAMIT ANG PLAYGROUND NA ITO?",
    intro: "Muling dinidisenyo namin ang General Hart Playground kasama ang input mula sa komunidad na tunay na gumagamit nito.",
    aboutLabel: "TUNGKOL SA PROYEKTONG ITO",
    aboutText: "Ang STREETOYSTER QUEENS ay nag-commission ng isang artist upang muling isipin ang playground na ito batay sa kung paano mo ito ginagamit.",
    aboutMeta: "Alex Tudela, katutubo ng Woodside\n2026 David Prize applicant\nNakikipag-usap sa NYC Parks at Community Board 2",
    share: "Ibahagi",
    vote: "Bumoto",
    timelineLabel: "ANO ANG SUSUNOD",
    timelineSteps: "→ Spring 2026: Nagbibigay ng feedback ang komunidad\n→ Summer 2026: Sinusuri ng artist ang input ng komunidad\n→ Fall 2026: Ibinahagi ang mga konsepto ng disenyo\n→ Spring 2027: Nagsisimula ang pag-install",
    followText: "Sundan ang proseso:",
    meta: "Bukas sa lahat · Anumang wika · Walang kailangang account",
    inspirationPrompt: "Gusto mo bang makita kung paano muling iniimagine ang ibang playground sa buong mundo?",
    inspirationPromptVote: "Gusto mo bang makita kung ano ang posible para sa espasyong ito?",
    designReferenceBtn: "Tuklasin ang mga sanggunian ng disenyo →",
    
    // Share flow
    shareStep1Label: "MAGBAHAGI NG LARAWAN",
    shareStep1Title: "IPAKITA SA AMIN KUNG PAANO MO GINAGAMIT ANG ESPASYONG ITO",
    shareStep1Helper: "Paglalaro, pahinga, pagtitipon, paghihintay, pagdaan—lahat ay mahalaga.",
    uploadPhoto: "KUMUHA O MAG-UPLOAD NG LARAWAN",
    skipStep: "LAKTAWAN ANG HAKBANG NA ITO",
    privacyNote: "Maaaring labo ang mga mukha\nMga larawan ginagamit lamang para sa pagpaplano ng disenyo\nPrivacidad ng mga bata protektado",
    shareStep2Label: "MAGDAGDAG NG KONTEKSTO (OPSYONAL)",
    shareStep2Title: "ANO ANG NANGYAYARI?",
    shareStep2Helper: "Isa o dalawang pangungusap ay perpekto. Magsulat sa anumang wika.",
    textareaPlaceholder: "Ang aking mga anak ay naghihintay dito pagkatapos ng klase dahil may lilim.",
    continueBtn: "MAGPATULOY",
    shareStep3Label: "KAILAN ITO?",
    shareStep3Title: "ORAS NG ARAW",
    shareStep3Helper: "Tumutulong sa amin na maunawaan kung kailan pinaka-ginagamit ang playground.",
    morning: "Umaga",
    afternoon: "Hapon",
    evening: "Gabi",
    finish: "TAPUSIN",
    shareStep4Title: "SALAMAT",
    shareStep4Text: "Ang iyong input ay tumutulong na hubugin ang disenyo ng artist.",
    updatesLabel: "KUMUHA NG MGA UPDATE SA PROYEKTO",
    emailPlaceholder: "ang-iyong@email.com (opsyonal)",
    emailMeta: "3-4 na email lang tungkol sa progreso ng disenyo. Walang spam.",
    done: "TAPOS NA",
    
    // Vote flow
    voteStep1Label: "ANG IYONG MGA PRIORIDAD",
    voteStep1Title: "ANO ANG DAPAT UNAHIN NG ARTIST?",
    voteInstructions: "Pumili ng dalawa o higit pang bagay na mahalaga sa iyo.",
    voteOptionShade: "Mas maraming lilim para sa mainit na araw",
    voteOptionSeating: "Upuan para sa mga lolo at lola at tagapag-alaga",
    voteOptionAges: "Paglalaro na gumagana para sa iba't ibang edad nang magkasama",
    voteOptionCultures: "Mga espasyo na pakiramdam na konektado sa ating mga kultura",
    voteOptionMovement: "Malikhaing paggalaw (hindi lang karaniwang kagamitan)",
    voteOptionGathering: "Mga lugar upang magtipon, hindi lang maglaro",
    voteOptionOther: "Iba pa",
    voteOtherPlaceholder: "Sabihin sa amin kung ano...",
    submitBtn: "ISUMITE",
    voteStep2Title: "ANG IYONG INPUT AY NABILANG NA",
    voteStep2Text: "Gagamitin ng artist ang mga prioridad na ito upang gabayan ang disenyo.",
    seeReferencesBtn: "TINGNAN ANG MGA SANGGUNIAN NG DISENYO →",
    shareActionLabel: "GUSTO MO BANG IBAHAGI KUNG PAANO MO GINAGAMIT ANG PLAYGROUND?",
    shareActionBtn: "MAGBAHAGI NG LARAWAN",
    
    // Alerts
    alertDescription: "Mangyaring magdagdag ng paglalarawan bago magpatuloy.",
    alertVote: "Mangyaring pumili ng hindi bababa sa dalawang opsyon.",
    alertVoteOtherEmpty: "Mangyaring ilarawan kung ano ang ibig sabihin ng 'Iba pa' para sa iyo."
  },
  
  bn: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "আপনি এই খেলার মাঠটি কীভাবে ব্যবহার করেন?",
    intro: "আমরা জেনারেল হার্ট খেলার মাঠ পুনরায় ডিজাইন করছি যারা প্রকৃতপক্ষে এটি ব্যবহার করেন তাদের ইনপুট সহ।",
    aboutLabel: "এই প্রকল্প সম্পর্কে",
    aboutText: "STREETOYSTER QUEENS একজন শিল্পীকে নিয়োগ দিচ্ছে আপনি কীভাবে এটি ব্যবহার করেন তার উপর ভিত্তি করে এই খেলার মাঠটি পুনর্কল্পনা করতে।",
    aboutMeta: "Alex Tudela, Woodside এর স্থানীয়\n2026 David Prize আবেদনকারী\nNYC Parks এবং Community Board 2 এর সাথে কথোপকথনে",
    share: "শেয়ার করুন",
    vote: "ভোট দিন",
    timelineLabel: "পরবর্তী কী ঘটবে",
    timelineSteps: "→ বসন্ত 2026: সম্প্রদায় প্রতিক্রিয়া প্রদান করে\n→ গ্রীষ্ম 2026: শিল্পী সম্প্রদায়ের ইনপুট পর্যালোচনা করেন\n→ শরৎ 2026: ডিজাইন ধারণা শেয়ার করা হয়\n→ বসন্ত 2027: ইনস্টলেশন শুরু হয়",
    followText: "প্রক্রিয়াটি অনুসরণ করুন:",
    meta: "সবার জন্য উন্মুক্ত · যেকোনো ভাষা · কোনো অ্যাকাউন্ট প্রয়োজন নেই",
    inspirationPrompt: "সারা বিশ্বে অন্যান্য খেলার মাঠ কীভাবে পুনর্কল্পনা করা হচ্ছে তা দেখতে চান?",
    inspirationPromptVote: "এই স্থানের জন্য কী সম্ভব তা দেখতে চান?",
    designReferenceBtn: "ডিজাইন রেফারেন্স অন্বেষণ করুন →",
    
    // Share flow
    shareStep1Label: "একটি ছবি শেয়ার করুন",
    shareStep1Title: "আমাদের দেখান আপনি কীভাবে এই স্থান ব্যবহার করেন",
    shareStep1Helper: "খেলা, বিশ্রাম, জমায়েত, অপেক্ষা, পাশ দিয়ে যাওয়া—সবকিছু গুরুত্বপূর্ণ।",
    uploadPhoto: "ছবি তুলুন বা আপলোড করুন",
    skipStep: "এই ধাপটি এড়িয়ে যান",
    privacyNote: "মুখ ঝাপসা করা যেতে পারে\nছবি শুধুমাত্র ডিজাইন পরিকল্পনার জন্য ব্যবহৃত\nশিশুদের গোপনীয়তা সুরক্ষিত",
    shareStep2Label: "প্রসঙ্গ যোগ করুন (ঐচ্ছিক)",
    shareStep2Title: "কী ঘটছে?",
    shareStep2Helper: "একটি বা দুটি বাক্য নিখুঁত। যেকোনো ভাষায় লিখুন।",
    textareaPlaceholder: "আমার বাচ্চারা স্কুলের পরে এখানে অপেক্ষা করে কারণ এখানে ছায়া আছে।",
    continueBtn: "চালিয়ে যান",
    shareStep3Label: "এটি কখন ছিল?",
    shareStep3Title: "দিনের সময়",
    shareStep3Helper: "খেলার মাঠটি কখন সবচেয়ে বেশি ব্যবহৃত হয় তা বুঝতে সাহায্য করে।",
    morning: "সকাল",
    afternoon: "বিকেল",
    evening: "সন্ধ্যা",
    finish: "শেষ করুন",
    shareStep4Title: "ধন্যবাদ",
    shareStep4Text: "আপনার ইনপুট শিল্পীর ডিজাইন গঠনে সাহায্য করবে।",
    updatesLabel: "প্রকল্পের আপডেট পান",
    emailPlaceholder: "আপনার@email.com (ঐচ্ছিক)",
    emailMeta: "ডিজাইন অগ্রগতি সম্পর্কে মোট 3-4টি ইমেল। স্প্যাম নেই।",
    done: "সম্পন্ন",
    
    // Vote flow
    voteStep1Label: "আপনার অগ্রাধিকার",
    voteStep1Title: "শিল্পীকে কী অগ্রাধিকার দিতে হবে?",
    voteInstructions: "আপনার কাছে গুরুত্বপূর্ণ দুটি বা তার বেশি জিনিস বেছে নিন।",
    voteOptionShade: "গরম দিনের জন্য আরও ছায়া",
    voteOptionSeating: "দাদা-দাদি এবং যত্নশীলদের জন্য বসার জায়গা",
    voteOptionAges: "বিভিন্ন বয়সের জন্য একসাথে কাজ করে এমন খেলা",
    voteOptionCultures: "আমাদের সংস্কৃতির সাথে সংযুক্ত মনে হয় এমন স্থান",
    voteOptionMovement: "সৃজনশীল আন্দোলন (শুধু মানক সরঞ্জাম নয়)",
    voteOptionGathering: "জড়ো হওয়ার জায়গা, শুধু খেলার নয়",
    voteOptionOther: "অন্যান্য",
    voteOtherPlaceholder: "আমাদের বলুন কী...",
    submitBtn: "জমা দিন",
    voteStep2Title: "আপনার ইনপুট গণনা করা হয়েছে",
    voteStep2Text: "শিল্পী ডিজাইন গাইড করতে এই অগ্রাধিকারগুলি ব্যবহার করবেন।",
    seeReferencesBtn: "ডিজাইন রেফারেন্স দেখুন →",
    shareActionLabel: "আপনি কীভাবে খেলার মাঠ ব্যবহার করেন শেয়ার করতে চান?",
    shareActionBtn: "একটি ছবি শেয়ার করুন",
    
    // Alerts
    alertDescription: "অব্যাহত রাখার আগে একটি বর্ণনা যোগ করুন।",
    alertVote: "অন্তত দুটি বিকল্প নির্বাচন করুন।",
    alertVoteOtherEmpty: "অনুগ্রহ করে 'অন্যান্য' এর অর্থ বর্ণনা করুন।"
  },
  
  ne: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "तपाईं यो खेल मैदान कसरी प्रयोग गर्नुहुन्छ?",
    intro: "हामी जनरल हार्ट खेल मैदान पुन: डिजाइन गर्दैछौं समुदायबाट इनपुट लिएर जसले वास्तवमा यसलाई प्रयोग गर्छ।",
    aboutLabel: "यो परियोजनाको बारेमा",
    aboutText: "STREETOYSTER QUEENS एक कलाकारलाई नियुक्त गर्दैछ तपाईंले यसलाई कसरी प्रयोग गर्नुहुन्छ भन्ने आधारमा यो खेल मैदान पुन: कल्पना गर्न।",
    aboutMeta: "Alex Tudela, Woodside को मूल निवासी\n2026 David Prize आवेदक\nNYC Parks र Community Board 2 सँग वार्तालापमा",
    share: "साझा गर्नुहोस्",
    vote: "मतदान गर्नुहोस्",
    timelineLabel: "अर्को के हुन्छ",
    timelineSteps: "→ वसन्त 2026: समुदायले प्रतिक्रिया प्रदान गर्छ\n→ गर्मी 2026: कलाकारले समुदाय इनपुट समीक्षा गर्छ\n→ शरद 2026: डिजाइन अवधारणाहरू साझा गरिन्छ\n→ वसन्त 2027: स्थापना सुरु हुन्छ",
    followText: "प्रक्रिया पालन गर्नुहोस्:",
    meta: "सबैका लागि खुला · कुनै पनि भाषा · कुनै खाता आवश्यक छैन",
    inspirationPrompt: "विश्वभर अन्य खेल मैदानहरू कसरी पुन: कल्पना गरिँदैछ हेर्न चाहनुहुन्छ?",
    inspirationPromptVote: "यो स्थानको लागि के सम्भव छ हेर्न चाहनुहुन्छ?",
    designReferenceBtn: "डिजाइन सन्दर्भहरू अन्वेषण गर्नुहोस् →",
    
    // Share flow
    shareStep1Label: "तस्बिर साझा गर्नुहोस्",
    shareStep1Title: "हामीलाई देखाउनुहोस् तपाईं यो स्थान कसरी प्रयोग गर्नुहुन्छ",
    shareStep1Helper: "खेल्ने, आराम गर्ने, भेला हुने, पर्खने, पार गर्ने—सबै महत्त्वपूर्ण छ।",
    uploadPhoto: "तस्बिर खिच्नुहोस् वा अपलोड गर्नुहोस्",
    skipStep: "यो चरण छोड्नुहोस्",
    privacyNote: "अनुहार धमिलो पार्न सकिन्छ\nतस्बिर केवल डिजाइन योजनाको लागि प्रयोग\nबालबालिकाको गोपनीयता सुरक्षित",
    shareStep2Label: "सन्दर्भ थप्नुहोस् (वैकल्पिक)",
    shareStep2Title: "के भइरहेको छ?",
    shareStep2Helper: "एक वा दुई वाक्य उत्तम छ। कुनै पनि भाषामा लेख्नुहोस्।",
    textareaPlaceholder: "मेरा बच्चाहरू स्कूल पछि यहाँ पर्खन्छन् किनभने यहाँ छाया छ।",
    continueBtn: "जारी राख्नुहोस्",
    shareStep3Label: "यो कहिले थियो?",
    shareStep3Title: "दिनको समय",
    shareStep3Helper: "खेल मैदान कहिले सबैभन्दा बढी प्रयोग गरिन्छ बुझ्न मद्दत गर्छ।",
    morning: "बिहान",
    afternoon: "दिउँसो",
    evening: "साँझ",
    finish: "समाप्त गर्नुहोस्",
    shareStep4Title: "धन्यवाद",
    shareStep4Text: "तपाईंको इनपुटले कलाकारको डिजाइन आकार दिन मद्दत गर्नेछ।",
    updatesLabel: "परियोजना अद्यावधिक प्राप्त गर्नुहोस्",
    emailPlaceholder: "तपाईंको@email.com (वैकल्पिक)",
    emailMeta: "डिजाइन प्रगति बारे कुल 3-4 इमेल। स्प्याम छैन।",
    done: "सम्पन्न",
    
    // Vote flow
    voteStep1Label: "तपाईंको प्राथमिकताहरू",
    voteStep1Title: "कलाकारले के प्राथमिकता दिनुपर्छ?",
    voteInstructions: "तपाईंलाई महत्त्वपूर्ण दुई वा बढी कुराहरू छान्नुहोस्।",
    voteOptionShade: "तातो दिनहरूको लागि थप छाया",
    voteOptionSeating: "हजुरबुबा हजुरआमा र हेरचाहकर्ताहरूको लागि बस्ने ठाउँ",
    voteOptionAges: "विभिन्न उमेरका लागि सँगै काम गर्ने खेल",
    voteOptionCultures: "हाम्रो संस्कृतिसँग जोडिएको महसुस हुने ठाउँहरू",
    voteOptionMovement: "सृजनात्मक आन्दोलन (केवल मानक उपकरण होइन)",
    voteOptionGathering: "भेला हुने ठाउँहरू, केवल खेल्ने होइन",
    voteOptionOther: "अन्य",
    voteOtherPlaceholder: "हामीलाई के भन्नुहोस्...",
    submitBtn: "पेश गर्नुहोस्",
    voteStep2Title: "तपाईंको इनपुट गणना गरिएको छ",
    voteStep2Text: "कलाकारले डिजाइन मार्गदर्शन गर्न यी प्राथमिकताहरू प्रयोग गर्नेछ।",
    seeReferencesBtn: "डिजाइन सन्दर्भहरू हेर्नुहोस् →",
    shareActionLabel: "तपाईं खेल मैदान कसरी प्रयोग गर्नुहुन्छ साझा गर्न चाहनुहुन्छ?",
    shareActionBtn: "तस्बिर साझा गर्नुहोस्",
    
    // Alerts
    alertDescription: "कृपया जारी राख्नु अघि विवरण थप्नुहोस्।",
    alertVote: "कृपया कम्तिमा दुई विकल्पहरू चयन गर्नुहोस्।",
    alertVoteOtherEmpty: "कृपया 'अन्य' को अर्थ वर्णन गर्नुहोस्।"
  },
  
  zh: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "您如何使用这个游乐场？",
    intro: "我们正在重新设计哈特将军游乐场，征求实际使用者的意见。",
    aboutLabel: "关于这个项目",
    aboutText: "STREETOYSTER QUEENS 正在委托一位艺术家根据您的使用方式重新构想这个游乐场。",
    aboutMeta: "Alex Tudela，伍德赛德本地人\n2026年David奖申请人\n与纽约市公园局和社区委员会2号对话中",
    share: "分享",
    vote: "投票",
    timelineLabel: "接下来会发生什么",
    timelineSteps: "→ 2026年春季：社区提供反馈\n→ 2026年夏季：艺术家审查社区意见\n→ 2026年秋季：分享设计概念\n→ 2027年春季：开始安装",
    followText: "关注进程：",
    meta: "向所有人开放 · 任何语言 · 无需账户",
    inspirationPrompt: "想看看世界各地的其他游乐场是如何重新构想的吗？",
    inspirationPromptVote: "想看看这个空间有什么可能吗？",
    designReferenceBtn: "探索设计参考 →",
    
    // Share flow
    shareStep1Label: "分享照片",
    shareStep1Title: "向我们展示您如何使用这个空间",
    shareStep1Helper: "玩耍、休息、聚会、等待、路过——一切都很重要。",
    uploadPhoto: "拍摄或上传照片",
    skipStep: "跳过此步骤",
    privacyNote: "面部可以模糊\n照片仅用于设计规划\n儿童隐私受保护",
    shareStep2Label: "添加背景（可选）",
    shareStep2Title: "发生了什么？",
    shareStep2Helper: "一两句话就很完美。用任何语言书写。",
    textareaPlaceholder: "我的孩子们放学后在这里等待，因为这里有阴凉。",
    continueBtn: "继续",
    shareStep3Label: "这是什么时候？",
    shareStep3Title: "一天中的时间",
    shareStep3Helper: "帮助我们了解游乐场何时使用最多。",
    morning: "早上",
    afternoon: "下午",
    evening: "晚上",
    finish: "完成",
    shareStep4Title: "谢谢",
    shareStep4Text: "您的意见将帮助塑造艺术家的设计。",
    updatesLabel: "获取项目更新",
    emailPlaceholder: "您的@email.com（可选）",
    emailMeta: "总共3-4封有关设计进展的电子邮件。无垃圾邮件。",
    done: "完成",
    
    // Vote flow
    voteStep1Label: "您的优先事项",
    voteStep1Title: "艺术家应该优先考虑什么？",
    voteInstructions: "选择两个或更多对您重要的事情。",
    voteOptionShade: "炎热天气的更多阴凉",
    voteOptionSeating: "为祖父母和看护者提供座位",
    voteOptionAges: "适合不同年龄一起玩的游戏",
    voteOptionCultures: "与我们文化相连的空间",
    voteOptionMovement: "创意运动（不仅仅是标准设备）",
    voteOptionGathering: "聚会场所，不仅仅是玩耍",
    voteOptionOther: "其他",
    voteOtherPlaceholder: "告诉我们什么...",
    submitBtn: "提交",
    voteStep2Title: "您的意见已被计算",
    voteStep2Text: "艺术家将使用这些优先事项来指导设计。",
    seeReferencesBtn: "查看设计参考 →",
    shareActionLabel: "想分享您如何使用游乐场吗？",
    shareActionBtn: "分享照片",
    
    // Alerts
    alertDescription: "请在继续之前添加描述。",
    alertVote: "请至少选择两个选项。",
    alertVoteOtherEmpty: "请描述'其他'对您的意义。"
  },
  
  sa: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "भवन्तः एतत् क्रीडाक्षेत्रं कथं उपयुञ्जते?",
    intro: "वयं जनरल हार्ट क्रीडाक्षेत्रं पुनः डिज़ाइन कुर्मः तेषां निवेशेन ये वास्तवतः एतत् उपयुञ्जन्ति।",
    aboutLabel: "अस्मिन् परियोजनायां विषये",
    aboutText: "STREETOYSTER QUEENS एकं कलाकारं नियुनक्ति एतत् क्रीडाक्षेत्रं पुनः कल्पयितुं भवन्तः कथं उपयुञ्जन्ति इत्यस्य आधारेण।",
    aboutMeta: "Alex Tudela, Woodside मूलनिवासी\n2026 David Prize आवेदकः\nNYC Parks तथा Community Board 2 सह वार्तालापे",
    share: "साझं करोतु",
    vote: "मतं ददातु",
    timelineLabel: "परं किं भविष्यति",
    timelineSteps: "→ वसन्तः 2026: समुदायः प्रतिक्रियां ददाति\n→ ग्रीष्मः 2026: कलाकारः समुदाय-निवेशं समीक्षते\n→ शरदः 2026: डिज़ाइन-अवधारणाः साझाः क्रियन्ते\n→ वसन्तः 2027: स्थापना आरभ्यते",
    followText: "प्रक्रियां अनुसरतु:",
    meta: "सर्वेभ्यः मुक्तम् · कापि भाषा · लेखा न आवश्यकी",
    inspirationPrompt: "किं भवान् विश्वे अन्येषु क्रीडाक्षेत्रेषु कथं पुनः कल्पना क्रियते इति द्रष्टुम् इच्छति?",
    inspirationPromptVote: "किं एतस्मै स्थानाय किं सम्भवम् इति द्रष्टुम् इच्छति?",
    designReferenceBtn: "डिज़ाइन-सन्दर्भान् अन्वेषयतु →",
    
    // Share flow
    shareStep1Label: "चित्रं साझं करोतु",
    shareStep1Title: "अस्मभ्यं दर्शयतु भवन्तः एतत् स्थानं कथं उपयुञ्जन्ति",
    shareStep1Helper: "क्रीडनम्, विश्रामः, समवायः, प्रतीक्षा, पारगमनम्—सर्वं महत्त्वपूर्णम्।",
    uploadPhoto: "चित्रं गृह्णातु वा उत्तारयतु",
    skipStep: "एतत् पदं त्यजतु",
    privacyNote: "मुखानि अस्पष्टानि कर्तुं शक्यन्ते\nचित्राणि केवलं डिज़ाइन-योजनायै उपयुज्यन्ते\nबालकानां गोपनीयता सुरक्षिता",
    shareStep2Label: "सन्दर्भं योजयतु (वैकल्पिकम्)",
    shareStep2Title: "किं भवति?",
    shareStep2Helper: "एकं द्वौ वा वाक्यौ सम्यक्। कस्यामपि भाषायां लिखतु।",
    textareaPlaceholder: "मम बालकाः विद्यालयात् अनन्तरं अत्र प्रतीक्षन्ते यतः अत्र छाया अस्ति।",
    continueBtn: "आगच्छतु",
    shareStep3Label: "एतत् कदा आसीत्?",
    shareStep3Title: "दिवसस्य समयः",
    shareStep3Helper: "क्रीडाक्षेत्रं कदा अधिकतमं उपयुज्यते इति बोधयितुं साहाय्यं करोति।",
    morning: "प्रातः",
    afternoon: "अपराह्णः",
    evening: "सायम्",
    finish: "समाप्नोतु",
    shareStep4Title: "धन्यवादः",
    shareStep4Text: "भवतः निवेशः कलाकारस्य डिज़ाइनं आकारयितुं साहाय्यं करिष्यति।",
    updatesLabel: "परियोजना-नूतनीकरणानि प्राप्नोतु",
    emailPlaceholder: "भवतः@email.com (वैकल्पिकम्)",
    emailMeta: "डिज़ाइन-प्रगतेः विषये कुलतः 3-4 ईमेलाः। स्पैमं नास्ति।",
    done: "समाप्तम्",
    
    // Vote flow
    voteStep1Label: "भवतः प्राथमिकताः",
    voteStep1Title: "कलाकारेण किं प्राथमिकतां दातव्यम्?",
    voteInstructions: "भवते महत्त्वपूर्णानि द्वौ अधिकान् वा विषयान् चिनोतु।",
    voteOptionShade: "उष्णदिनेभ्यः अधिकं छाया",
    voteOptionSeating: "पितामहेभ्यः परिचारकेभ्यः च उपवेशनम्",
    voteOptionAges: "विभिन्नवयसां कृते मिलित्वा कार्यं करोति यत् क्रीडा",
    voteOptionCultures: "अस्माकं संस्कृत्या सह सम्बद्धं अनुभूयते यत् स्थानानि",
    voteOptionMovement: "सृजनात्मकं गतिः (केवलं मानक-उपकरणं न)",
    voteOptionGathering: "समवेतुं स्थानानि, केवलं क्रीडितुं न",
    voteOptionOther: "अन्यत्",
    voteOtherPlaceholder: "अस्मभ्यं वदतु किं...",
    submitBtn: "समर्पयतु",
    voteStep2Title: "भवतः निवेशः गणितः",
    voteStep2Text: "कलाकारः डिज़ाइनं मार्गदर्शयितुं एताः प्राथमिकताः उपयोक्ष्यते।",
    seeReferencesBtn: "डिज़ाइन-सन्दर्भान् पश्यतु →",
    shareActionLabel: "भवान् क्रीडाक्षेत्रं कथं उपयुनक्ति इति साझं कर्तुम् इच्छति वा?",
    shareActionBtn: "चित्रं साझं करोतु",
    
    // Alerts
    alertDescription: "कृपया आगे बढ़ने से पूर्वं विवरणं योजयतु।",
    alertVote: "कृपया न्यूनतमं द्वौ विकल्पौ चिनोतु।",
    alertVoteOtherEmpty: "कृपया 'अन्यत्' इत्यस्य अर्थं वर्णयतु।"
  }
};
