const translations = {
  en: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "HOW DO YOU USE THIS PLAYGROUND?",
    intro: "We're redesigning General Hart Playground with input from the community who actually uses it.",
    aboutLabel: "ABOUT THIS PROJECT",
    aboutText: "STREETOYSTER QUEENS is commissioning an artist to reimagine this playground based on how you use it.",
    aboutMeta: "Alex Tudela, Woodside native\n2026 David Prize applicant\nIn conversation with NYC Parks & Community Board 2",
    share: "SHARE PHOTOS",
    vote: "TELL US",
    timelineLabel: "WHAT HAPPENS NEXT",
    timelineSteps: "→ Summer 2026: Artist reviews community input\n→ Fall 2026: Design concepts shared with community\n→ Winter 2026: Final design approved\n→ Spring 2027: Installation begins",
    followText: "Follow the process:",
    meta: "Open to all · Any language · No account needed",
    inspirationPrompt: "Want to see how other playgrounds are being reimagined around the world?",
    inspirationPromptVote: "Want to see what's possible for this space?",
    designReferenceBtn: "Explore design references →",
    
    // Share flow
    shareStep1Label: "SHARE A PHOTO",
    shareStep1Title: "SHOW US HOW YOU USE THIS SPACE",
    shareStep1Helper: "Playing, resting, gathering, waiting, passing through—it all matters.",
    uploadPhoto: "TAKE PHOTO",
    skipStep: "SKIP THIS STEP",
    privacyNote: "Privacy protected: Faces can be blurred, photos used only for design planning and not published publicly.",
    shareStep2Label: "TELL US MORE (OPTIONAL)",
    shareStep2Title: "WHAT'S HAPPENING?",
    shareStep2Helper: "A sentence or two is perfect. Write in any language.",
    textareaPlaceholder: "My kids wait here after school because there's shade.",
    continueBtn: "CONTINUE",
    shareStep3Label: "WHEN DO YOU USE THIS PARK?",
    shareStep3Title: "TIME OF DAY",
    shareStep3Helper: "Helps us understand when the playground is most used.",
    morning: "Morning",
    afternoon: "Afternoon",
    evening: "Evening",
    finish: "FINISH",
    shareStep4Title: "THANK YOU",
    shareStep4Text: "Your input will help shape the artist's design.",
    updatesLabel: "GET PROJECT UPDATES",
    emailPlaceholder: "your@email.com (optional)",
    emailMeta: "3-4 emails total about design progress. No spam.",
    done: "DONE",
    
    // Vote flow
    voteStep1Label: "YOUR PRIORITIES",
    voteStep1Title: "WHAT SHOULD THE ARTIST PRIORITIZE?",
    voteInstructions: "Pick two or more things that matter to you.",
    voteOptionShade: "More shade for hot days",
    voteOptionSeating: "SEATING (FOR CAREGIVERS & GRANDPARENTS)",
    voteOptionAges: "Play that works for different ages together",
    voteOptionCultures: "Spaces that feel connected to our cultures",
    voteOptionMovement: "Creative movement (not just standard equipment)",
    voteOptionGathering: "Places to gather, not just play",
    voteOptionOther: "Other",
    voteOtherPlaceholder: "Tell us what...",
    submitBtn: "SUBMIT",
    voteStep2Title: "YOUR INPUT HAS BEEN COUNTED",
    voteStep2Text: "The artist will use these priorities to guide the design.",
    seeReferencesBtn: "SEE DESIGN REFERENCES →",
    shareActionLabel: "WANT TO SHARE HOW YOU USE THE PLAYGROUND?",
    shareActionBtn: "SHARE A PHOTO",
    
    // Alerts
    alertDescription: "Please add a description before continuing.",
    alertVote: "Please select at least two options.",
    alertVoteOtherEmpty: "Please describe what 'Other' means to you."
  },
  
  es: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "¿CÓMO USA ESTE PATIO?",
    intro: "Estamos rediseñando el parque General Hart con aportes de la comunidad que realmente lo usa.",
    aboutLabel: "SOBRE ESTE PROYECTO",
    aboutText: "STREETOYSTER QUEENS está comisionando a un artista para reimaginar este patio según cómo lo uses.",
    aboutMeta: "Alex Tudela, nativo de Woodside\nCandidato al Premio David 2026\nEn conversación con NYC Parks y Community Board 2",
    share: "COMPARTIR FOTOS",
    vote: "CUÉNTANOS",
    timelineLabel: "QUÉ SIGUE",
    timelineSteps: "→ Verano 2026: El artista revisa los aportes de la comunidad\n→ Otoño 2026: Conceptos de diseño compartidos con la comunidad\n→ Invierno 2026: Diseño final aprobado\n→ Primavera 2027: Comienza la instalación",
    followText: "Siga el proceso:",
    meta: "Abierto a todos · Cualquier idioma · No se necesita cuenta",
    inspirationPrompt: "¿Quiere ver cómo se están reimaginando otros parques infantiles en todo el mundo?",
    inspirationPromptVote: "¿Quiere ver qué es posible para este espacio?",
    designReferenceBtn: "Explorar referencias de diseño →",
    
    // Share flow
    shareStep1Label: "COMPARTIR UNA FOTO",
    shareStep1Title: "MUÉSTRANOS CÓMO USAS ESTE ESPACIO",
    shareStep1Helper: "Jugar, descansar, reunirse, esperar, pasar—todo importa.",
    uploadPhoto: "TOMAR FOTO",
    skipStep: "SALTAR ESTE PASO",
    privacyNote: "Privacidad protegida: Los rostros pueden difuminarse, fotos usadas solo para planificación de diseño y no se publican públicamente.",
    shareStep2Label: "CUÉNTANOS MÁS (OPCIONAL)",
    shareStep2Title: "¿QUÉ ESTÁ PASANDO?",
    shareStep2Helper: "Una o dos oraciones es perfecto. Escriba en cualquier idioma.",
    textareaPlaceholder: "Mis hijos esperan aquí después de la escuela porque hay sombra.",
    continueBtn: "CONTINUAR",
    shareStep3Label: "¿CUÁNDO USA ESTE PARQUE?",
    shareStep3Title: "HORA DEL DÍA",
    shareStep3Helper: "Nos ayuda a entender cuándo el parque es más usado.",
    morning: "Mañana",
    afternoon: "Tarde",
    evening: "Noche",
    finish: "TERMINAR",
    shareStep4Title: "GRACIAS",
    shareStep4Text: "Su aporte ayudará a dar forma al diseño del artista.",
    updatesLabel: "RECIBIR ACTUALIZACIONES DEL PROYECTO",
    emailPlaceholder: "su@email.com (opcional)",
    emailMeta: "3-4 correos en total sobre el progreso del diseño. Sin spam.",
    done: "HECHO",
    
    // Vote flow
    voteStep1Label: "SUS PRIORIDADES",
    voteStep1Title: "¿QUÉ DEBE PRIORIZAR EL ARTISTA?",
    voteInstructions: "Elija dos o más cosas que le importen.",
    voteOptionShade: "Más sombra para días calurosos",
    voteOptionSeating: "ASIENTOS (PARA CUIDADORES Y ABUELOS)",
    voteOptionAges: "Juego que funcione para diferentes edades juntas",
    voteOptionCultures: "Espacios que se sientan conectados a nuestras culturas",
    voteOptionMovement: "Movimiento creativo (no solo equipo estándar)",
    voteOptionGathering: "Lugares para reunirse, no solo jugar",
    voteOptionOther: "Otro",
    voteOtherPlaceholder: "Díganos qué...",
    submitBtn: "ENVIAR",
    voteStep2Title: "SU OPINIÓN HA SIDO CONTADA",
    voteStep2Text: "El artista usará estas prioridades para guiar el diseño.",
    seeReferencesBtn: "VER REFERENCIAS DE DISEÑO →",
    shareActionLabel: "¿QUIERE COMPARTIR CÓMO USA EL PARQUE?",
    shareActionBtn: "COMPARTIR UNA FOTO",
    
    // Alerts
    alertDescription: "Por favor agregue una descripción antes de continuar.",
    alertVote: "Por favor seleccione al menos dos opciones.",
    alertVoteOtherEmpty: "Por favor describa qué significa 'Otro' para usted."
  },
  
  tl: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "PAANO MO GINAGAMIT ANG PLAYGROUND NA ITO?",
    intro: "Muling dinidisenyo namin ang General Hart Playground kasama ang input mula sa komunidad na tunay na gumagamit nito.",
    aboutLabel: "TUNGKOL SA PROYEKTONG ITO",
    aboutText: "Ang STREETOYSTER QUEENS ay nag-commission ng isang artist upang muling isipin ang playground na ito batay sa kung paano mo ito ginagamit.",
    aboutMeta: "Alex Tudela, katutubo ng Woodside\n2026 David Prize applicant\nNakikipag-usap sa NYC Parks at Community Board 2",
    share: "MAGBAHAGI NG MGA LARAWAN",
    vote: "SABIHIN SA AMIN",
    timelineLabel: "ANO ANG SUSUNOD",
    timelineSteps: "→ Summer 2026: Sinusuri ng artist ang input ng komunidad\n→ Fall 2026: Konsepto ng disenyo na ibinahagi sa komunidad\n→ Winter 2026: Pinal na disenyo ay naaprubahan\n→ Spring 2027: Nagsisimula ang pag-install",
    followText: "Sundan ang proseso:",
    meta: "Bukas sa lahat · Anumang wika · Walang kailangang account",
    inspirationPrompt: "Gusto mo bang makita kung paano muling iniimagine ang ibang playground sa buong mundo?",
    inspirationPromptVote: "Gusto mo bang makita kung ano ang posible para sa espasyong ito?",
    designReferenceBtn: "Tuklasin ang mga sanggunian ng disenyo →",
    
    // Share flow
    shareStep1Label: "MAGBAHAGI NG LARAWAN",
    shareStep1Title: "IPAKITA SA AMIN KUNG PAANO MO GINAGAMIT ANG ESPASYONG ITO",
    shareStep1Helper: "Paglalaro, pahinga, pagtitipon, paghihintay, pagdaan—lahat ay mahalaga.",
    uploadPhoto: "KUMUHA NG LARAWAN",
    skipStep: "LAKTAWAN ANG HAKBANG NA ITO",
    privacyNote: "Protektado ang privacy: Maaaring labo ang mga mukha, mga larawan ay ginagamit lamang para sa pagpaplano ng disenyo at hindi inilalathala sa publiko.",
    shareStep2Label: "SABIHIN SA AMIN ANG HIGIT PA (OPSYONAL)",
    shareStep2Title: "ANO ANG NANGYAYARI?",
    shareStep2Helper: "Isa o dalawang pangungusap ay perpekto. Magsulat sa anumang wika.",
    textareaPlaceholder: "Ang aking mga anak ay naghihintay dito pagkatapos ng klase dahil may lilim.",
    continueBtn: "MAGPATULOY",
    shareStep3Label: "KAILAN MO GINAGAMIT ANG PARK NA ITO?",
    shareStep3Title: "ORAS NG ARAW",
    shareStep3Helper: "Tumutulong sa amin na maunawaan kung kailan pinaka-ginagamit ang playground.",
    morning: "Umaga",
    afternoon: "Hapon",
    evening: "Gabi",
    finish: "TAPUSIN",
    shareStep4Title: "SALAMAT",
    shareStep4Text: "Ang iyong input ay tumutulong na hubugin ang disenyo ng artist.",
    updatesLabel: "KUMUHA NG MGA UPDATE SA PROYEKTO",
    emailPlaceholder: "ang-iyong@email.com (opsyonal)",
    emailMeta: "3-4 na email lang tungkol sa progreso ng disenyo. Walang spam.",
    done: "TAPOS NA",
    
    // Vote flow
    voteStep1Label: "ANG IYONG MGA PRIORIDAD",
    voteStep1Title: "ANO ANG DAPAT UNAHIN NG ARTIST?",
    voteInstructions: "Pumili ng dalawa o higit pang bagay na mahalaga sa iyo.",
    voteOptionShade: "Mas maraming lilim para sa mainit na araw",
    voteOptionSeating: "UPUAN (PARA SA MGA TAGAPAG-ALAGA AT LOLO/LOLA)",
    voteOptionAges: "Paglalaro na gumagana para sa iba't ibang edad nang magkasama",
    voteOptionCultures: "Mga espasyo na pakiramdam na konektado sa ating mga kultura",
    voteOptionMovement: "Malikhaing paggalaw (hindi lang karaniwang kagamitan)",
    voteOptionGathering: "Mga lugar upang magtipon, hindi lang maglaro",
    voteOptionOther: "Iba pa",
    voteOtherPlaceholder: "Sabihin sa amin kung ano...",
    submitBtn: "ISUMITE",
    voteStep2Title: "ANG IYONG INPUT AY NABILANG NA",
    voteStep2Text: "Gagamitin ng artist ang mga prioridad na ito upang gabayan ang disenyo.",
    seeReferencesBtn: "TINGNAN ANG MGA SANGGUNIAN NG DISENYO →",
    shareActionLabel: "GUSTO MO BANG IBAHAGI KUNG PAANO MO GINAGAMIT ANG PLAYGROUND?",
    shareActionBtn: "MAGBAHAGI NG LARAWAN",
    
    // Alerts
    alertDescription: "Mangyaring magdagdag ng paglalarawan bago magpatuloy.",
    alertVote: "Mangyaring pumili ng hindi bababa sa dalawang opsyon.",
    alertVoteOtherEmpty: "Mangyaring ilarawan kung ano ang ibig sabihin ng 'Iba pa' para sa iyo."
  },
  
  bn: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "আপনি এই খেলার মাঠটি কীভাবে ব্যবহার করেন?",
    intro: "আমরা জেনারেল হার্ট খেলার মাঠ পুনরায় ডিজাইন করছি যারা প্রকৃতপক্ষে এটি ব্যবহার করেন তাদের ইনপুট সহ।",
    aboutLabel: "এই প্রকল্প সম্পর্কে",
    aboutText: "STREETOYSTER QUEENS একজন শিল্পীকে নিয়োগ দিচ্ছে আপনি কীভাবে এটি ব্যবহার করেন তার উপর ভিত্তি করে এই খেলার মাঠটি পুনর্কল্পনা করতে।",
    aboutMeta: "Alex Tudela, Woodside এর স্থানীয়\n2026 David Prize আবেদনকারী\nNYC Parks এবং Community Board 2 এর সাথে কথোপকথনে",
    share: "ছবি শেয়ার করুন",
    vote: "আমাদের বলুন",
    timelineLabel: "পরবর্তী কী ঘটবে",
    timelineSteps: "→ গ্রীষ্ম 2026: শিল্পী সম্প্রদায়ের ইনপুট পর্যালোচনা করেন\n→ শরৎ 2026: সম্প্রদায়ের সাথে ডিজাইন ধারণা শেয়ার করা হয়\n→ শীত 2026: চূড়ান্ত ডিজাইন অনুমোদিত\n→ বসন্ত 2027: ইনস্টলেশন শুরু হয়",
    followText: "প্রক্রিয়াটি অনুসরণ করুন:",
    meta: "সবার জন্য উন্মুক্ত · যেকোনো ভাষা · কোনো অ্যাকাউন্ট প্রয়োজন নেই",
    inspirationPrompt: "সারা বিশ্বে অন্যান্য খেলার মাঠ কীভাবে পুনর্কল্পনা করা হচ্ছে তা দেখতে চান?",
    inspirationPromptVote: "এই স্থানের জন্য কী সম্ভব তা দেখতে চান?",
    designReferenceBtn: "ডিজাইন রেফারেন্স অন্বেষণ করুন →",
    
    // Share flow
    shareStep1Label: "একটি ছবি শেয়ার করুন",
    shareStep1Title: "আমাদের দেখান আপনি কীভাবে এই স্থান ব্যবহার করেন",
    shareStep1Helper: "খেলা, বিশ্রাম, জমায়েত, অপেক্ষা, পাশ দিয়ে যাওয়া—সবকিছু গুরুত্বপূর্ণ।",
    uploadPhoto: "ছবি তুলুন",
    skipStep: "এই ধাপটি এড়িয়ে যান",
    privacyNote: "গোপনীয়তা সুরক্ষিত: মুখ ঝাপসা করা যেতে পারে, ছবি শুধুমাত্র ডিজাইন পরিকল্পনার জন্য ব্যবহৃত এবং প্রকাশ্যে প্রকাশিত হয় না।",
    shareStep2Label: "আমাদের আরও বলুন (ঐচ্ছিক)",
    shareStep2Title: "কী ঘটছে?",
    shareStep2Helper: "একটি বা দুটি বাক্য নিখুঁত। যেকোনো ভাষায় লিখুন।",
    textareaPlaceholder: "আমার বাচ্চারা স্কুলের পরে এখানে অপেক্ষা করে কারণ এখানে ছায়া আছে।",
    continueBtn: "চালিয়ে যান",
    shareStep3Label: "আপনি কখন এই পার্ক ব্যবহার করেন?",
    shareStep3Title: "দিনের সময়",
    shareStep3Helper: "খেলার মাঠটি কখন সবচেয়ে বেশি ব্যবহৃত হয় তা বুঝতে সাহায্য করে।",
    morning: "সকাল",
    afternoon: "বিকেল",
    evening: "সন্ধ্যা",
    finish: "শেষ করুন",
    shareStep4Title: "ধন্যবাদ",
    shareStep4Text: "আপনার ইনপুট শিল্পীর ডিজাইন গঠনে সাহায্য করবে।",
    updatesLabel: "প্রকল্পের আপডেট পান",
    emailPlaceholder: "আপনার@email.com (ঐচ্ছিক)",
    emailMeta: "ডিজাইন অগ্রগতি সম্পর্কে মোট 3-4টি ইমেল। স্প্যাম নেই।",
    done: "সম্পন্ন",
    
    // Vote flow
    voteStep1Label: "আপনার অগ্রাধিকার",
    voteStep1Title: "শিল্পীকে কী অগ্রাধিকার দিতে হবে?",
    voteInstructions: "আপনার কাছে গুরুত্বপূর্ণ দুটি বা তার বেশি জিনিস বেছে নিন।",
    voteOptionShade: "গরম দিনের জন্য আরও ছায়া",
    voteOptionSeating: "বসার জায়গা (যত্নশীল ও দাদা-দাদির জন্য)",
    voteOptionAges: "বিভিন্ন বয়সের জন্য একসাথে কাজ করে এমন খেলা",
    voteOptionCultures: "আমাদের সংস্কৃতির সাথে সংযুক্ত মনে হয় এমন স্থান",
    voteOptionMovement: "সৃজনশীল আন্দোলন (শুধু মানক সরঞ্জাম নয়)",
    voteOptionGathering: "জড়ো হওয়ার জায়গা, শুধু খেলার নয়",
    voteOptionOther: "অন্যান্য",
    voteOtherPlaceholder: "আমাদের বলুন কী...",
    submitBtn: "জমা দিন",
    voteStep2Title: "আপনার ইনপুট গণনা করা হয়েছে",
    voteStep2Text: "শিল্পী ডিজাইন গাইড করতে এই অগ্রাধিকারগুলি ব্যবহার করবেন।",
    seeReferencesBtn: "ডিজাইন রেফারেন্স দেখুন →",
    shareActionLabel: "আপনি কীভাবে খেলার মাঠ ব্যবহার করেন শেয়ার করতে চান?",
    shareActionBtn: "একটি ছবি শেয়ার করুন",
    
    // Alerts
    alertDescription: "অব্যাহত রাখার আগে একটি বর্ণনা যোগ করুন।",
    alertVote: "অন্তত দুটি বিকল্প নির্বাচন করুন।",
    alertVoteOtherEmpty: "অনুগ্রহ করে 'অন্যান্য' এর অর্থ বর্ণনা করুন।"
  },
  
  ne: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "तपाईं यो खेल मैदान कसरी प्रयोग गर्नुहुन्छ?",
    intro: "हामी जनरल हार्ट खेल मैदान पुन: डिजाइन गर्दैछौं समुदायबाट इनपुट लिएर जसले वास्तवमा यसलाई प्रयोग गर्छ।",
    aboutLabel: "यो परियोजनाको बारेमा",
    aboutText: "STREETOYSTER QUEENS एक कलाकारलाई नियुक्त गर्दैछ तपाईंले यसलाई कसरी प्रयोग गर्नुहुन्छ भन्ने आधारमा यो खेल मैदान पुन: कल्पना गर्न।",
    aboutMeta: "Alex Tudela, Woodside को मूल निवासी\n2026 David Prize आवेदक\nNYC Parks र Community Board 2 सँग वार्तालापमा",
    share: "तस्बिरहरू साझा गर्नुहोस्",
    vote: "हामीलाई भन्नुहोस्",
    timelineLabel: "अर्को के हुन्छ",
    timelineSteps: "→ गर्मी 2026: कलाकारले समुदाय इनपुट समीक्षा गर्छ\n→ शरद 2026: समुदायसँग डिजाइन अवधारणाहरू साझा गरिन्छ\n→ हिउँद 2026: अन्तिम डिजाइन स्वीकृत\n→ वसन्त 2027: स्थापना सुरु हुन्छ",
    followText: "प्रक्रिया पालन गर्नुहोस्:",
    meta: "सबैका लागि खुला · कुनै पनि भाषा · कुनै खाता आवश्यक छैन",
    inspirationPrompt: "विश्वभर अन्य खेल मैदानहरू कसरी पुन: कल्पना गरिँदैछ हेर्न चाहनुहुन्छ?",
    inspirationPromptVote: "यो स्थानको लागि के सम्भव छ हेर्न चाहनुहुन्छ?",
    designReferenceBtn: "डिजाइन सन्दर्भहरू अन्वेषण गर्नुहोस् →",
    
    // Share flow
    shareStep1Label: "तस्बिर साझा गर्नुहोस्",
    shareStep1Title: "हामीलाई देखाउनुहोस् तपाईं यो स्थान कसरी प्रयोग गर्नुहुन्छ",
    shareStep1Helper: "खेल्ने, आराम गर्ने, भेला हुने, पर्खने, पार गर्ने—सबै महत्त्वपूर्ण छ।",
    uploadPhoto: "तस्बिर खिच्नुहोस्",
    skipStep: "यो चरण छोड्नुहोस्",
    privacyNote: "गोपनीयता सुरक्षित: अनुहार धमिलो पार्न सकिन्छ, तस्बिर केवल डिजाइन योजनाको लागि प्रयोग गरिन्छ र सार्वजनिक रूपमा प्रकाशित गरिँदैन।",
    shareStep2Label: "हामीलाई थप भन्नुहोस् (वैकल्पिक)",
    shareStep2Title: "के भइरहेको छ?",
    shareStep2Helper: "एक वा दुई वाक्य उत्तम छ। कुनै पनि भाषामा लेख्नुहोस्।",
    textareaPlaceholder: "मेरा बच्चाहरू स्कूल पछि यहाँ पर्खन्छन् किनभने यहाँ छाया छ।",
    continueBtn: "जारी राख्नुहोस्",
    shareStep3Label: "तपाईं यो पार्क कहिले प्रयोग गर्नुहुन्छ?",
    shareStep3Title: "दिनको समय",
    shareStep3Helper: "खेल मैदान कहिले सबैभन्दा बढी प्रयोग गरिन्छ बुझ्न मद्दत गर्छ।",
    morning: "बिहान",
    afternoon: "दिउँसो",
    evening: "साँझ",
    finish: "समाप्त गर्नुहोस्",
    shareStep4Title: "धन्यवाद",
    shareStep4Text: "तपाईंको इनपुटले कलाकारको डिजाइन आकार दिन मद्दत गर्नेछ।",
    updatesLabel: "परियोजना अद्यावधिक प्राप्त गर्नुहोस्",
    emailPlaceholder: "तपाईंको@email.com (वैकल्पिक)",
    emailMeta: "डिजाइन प्रगति बारे कुल 3-4 इमेल। स्प्याम छैन।",
    done: "सम्पन्न",
    
    // Vote flow
    voteStep1Label: "तपाईंको प्राथमिकताहरू",
    voteStep1Title: "कलाकारले के प्राथमिकता दिनुपर्छ?",
    voteInstructions: "तपाईंलाई महत्त्वपूर्ण दुई वा बढी कुराहरू छान्नुहोस्।",
    voteOptionShade: "तातो दिनहरूको लागि थप छाया",
    voteOptionSeating: "बस्ने ठाउँ (हेरचाहकर्ता र हजुरबा-हजुरआमाको लागि)",
    voteOptionAges: "विभिन्न उमेरका लागि सँगै काम गर्ने खेल",
    voteOptionCultures: "हाम्रो संस्कृतिसँग जोडिएको महसुस हुने ठाउँहरू",
    voteOptionMovement: "सृजनात्मक आन्दोलन (केवल मानक उपकरण होइन)",
    voteOptionGathering: "भेला हुने ठाउँहरू, केवल खेल्ने होइन",
    voteOptionOther: "अन्य",
    voteOtherPlaceholder: "हामीलाई के भन्नुहोस्...",
    submitBtn: "पेश गर्नुहोस्",
    voteStep2Title: "तपाईंको इनपुट गणना गरिएको छ",
    voteStep2Text: "कलाकारले डिजाइन मार्गदर्शन गर्न यी प्राथमिकताहरू प्रयोग गर्नेछ।",
    seeReferencesBtn: "डिजाइन सन्दर्भहरू हेर्नुहोस् →",
    shareActionLabel: "तपाईं खेल मैदान कसरी प्रयोग गर्नुहुन्छ साझा गर्न चाहनुहुन्छ?",
    shareActionBtn: "तस्बिर साझा गर्नुहोस्",
    
    // Alerts
    alertDescription: "कृपया जारी राख्नु अघि विवरण थप्नुहोस्।",
    alertVote: "कृपया कम्तिमा दुई विकल्पहरू चयन गर्नुहोस्।",
    alertVoteOtherEmpty: "कृपया 'अन्य' को अर्थ वर्णन गर्नुहोस्।"
  },
  
  zh: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "您如何使用这个游乐场？",
    intro: "我们正在重新设计哈特将军游乐场，征求实际使用者的意见。",
    aboutLabel: "关于这个项目",
    aboutText: "STREETOYSTER QUEENS 正在委托一位艺术家根据您的使用方式重新构想这个游乐场。",
    aboutMeta: "Alex Tudela，伍德赛德本地人\n2026年David奖申请人\n与纽约市公园局和社区委员会2号对话中",
    share: "分享照片",
    vote: "告诉我们",
    timelineLabel: "接下来会发生什么",
    timelineSteps: "→ 2026年夏季：艺术家审查社区意见\n→ 2026年秋季：与社区分享设计概念\n→ 2026年冬季：最终设计获批\n→ 2027年春季：开始安装",
    followText: "关注进程：",
    meta: "向所有人开放 · 任何语言 · 无需账户",
    inspirationPrompt: "想看看世界各地的其他游乐场是如何重新构想的吗？",
    inspirationPromptVote: "想看看这个空间有什么可能吗？",
    designReferenceBtn: "探索设计参考 →",
    
    // Share flow
    shareStep1Label: "分享照片",
    shareStep1Title: "向我们展示您如何使用这个空间",
    shareStep1Helper: "玩耍、休息、聚会、等待、路过——一切都很重要。",
    uploadPhoto: "拍摄照片",
    skipStep: "跳过此步骤",
    privacyNote: "隐私受保护：面部可以模糊，照片仅用于设计规划，不会公开发布。",
    shareStep2Label: "告诉我们更多（可选）",
    shareStep2Title: "发生了什么？",
    shareStep2Helper: "一两句话就很完美。用任何语言书写。",
    textareaPlaceholder: "我的孩子们放学后在这里等待，因为这里有阴凉。",
    continueBtn: "继续",
    shareStep3Label: "您什么时候使用这个公园？",
    shareStep3Title: "一天中的时间",
    shareStep3Helper: "帮助我们了解游乐场何时使用最多。",
    morning: "早上",
    afternoon: "下午",
    evening: "晚上",
    finish: "完成",
    shareStep4Title: "谢谢",
    shareStep4Text: "您的意见将帮助塑造艺术家的设计。",
    updatesLabel: "获取项目更新",
    emailPlaceholder: "您的@email.com（可选）",
    emailMeta: "总共3-4封有关设计进展的电子邮件。无垃圾邮件。",
    done: "完成",
    
    // Vote flow
    voteStep1Label: "您的优先事项",
    voteStep1Title: "艺术家应该优先考虑什么？",
    voteInstructions: "选择两个或更多对您重要的事情。",
    voteOptionShade: "炎热天气的更多阴凉",
    voteOptionSeating: "座位（为看护者和祖父母提供）",
    voteOptionAges: "适合不同年龄一起玩的游戏",
    voteOptionCultures: "与我们文化相连的空间",
    voteOptionMovement: "创意运动（不仅仅是标准设备）",
    voteOptionGathering: "聚会场所，不仅仅是玩耍",
    voteOptionOther: "其他",
    voteOtherPlaceholder: "告诉我们什么...",
    submitBtn: "提交",
    voteStep2Title: "您的意见已被计算",
    voteStep2Text: "艺术家将使用这些优先事项来指导设计。",
    seeReferencesBtn: "查看设计参考 →",
    shareActionLabel: "想分享您如何使用游乐场吗？",
    shareActionBtn: "分享照片",
    
    // Alerts
    alertDescription: "请在继续之前添加描述。",
    alertVote: "请至少选择两个选项。",
    alertVoteOtherEmpty: "请描述'其他'对您的意义。"
  },
  
  ko: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "이 놀이터를 어떻게 사용하시나요?",
    intro: "우리는 실제로 사용하는 커뮤니티의 의견을 받아 General Hart 놀이터를 재설계하고 있습니다.",
    aboutLabel: "이 프로젝트에 대하여",
    aboutText: "STREETOYSTER QUEENS는 여러분이 사용하는 방식을 바탕으로 이 놀이터를 재구상할 예술가를 위촉하고 있습니다.",
    aboutMeta: "Alex Tudela, Woodside 거주민\n2026 David Prize 지원자\nNYC Parks 및 Community Board 2와 협의 중",
    share: "사진 공유",
    vote: "의견 전하기",
    timelineLabel: "다음 단계",
    timelineSteps: "→ 2026년 여름: 예술가가 커뮤니티 의견 검토\n→ 2026년 가을: 커뮤니티와 디자인 컨셉 공유\n→ 2026년 겨울: 최종 디자인 승인\n→ 2027년 봄: 설치 시작",
    followText: "진행 과정 팔로우:",
    meta: "모두에게 열려있음 · 모든 언어 환영 · 계정 불필요",
    inspirationPrompt: "전 세계의 다른 놀이터가 어떻게 재구상되고 있는지 보시겠습니까?",
    inspirationPromptVote: "이 공간에서 무엇이 가능한지 보시겠습니까?",
    designReferenceBtn: "디자인 참고자료 탐색 →",
    
    // Share flow
    shareStep1Label: "사진 공유",
    shareStep1Title: "이 공간을 어떻게 사용하는지 보여주세요",
    shareStep1Helper: "놀기, 쉬기, 모이기, 기다리기, 지나가기—모든 것이 중요합니다.",
    uploadPhoto: "사진 촬영",
    skipStep: "이 단계 건너뛰기",
    privacyNote: "개인정보 보호: 얼굴 흐림 처리 가능, 사진은 디자인 계획에만 사용되며 공개적으로 게시되지 않습니다.",
    shareStep2Label: "더 자세히 알려주세요 (선택사항)",
    shareStep2Title: "무엇이 일어나고 있나요?",
    shareStep2Helper: "한두 문장이면 완벽합니다. 모든 언어로 작성하세요.",
    textareaPlaceholder: "제 아이들은 그늘이 있어서 방과 후 여기서 기다립니다.",
    continueBtn: "계속",
    shareStep3Label: "이 공원을 언제 사용하시나요?",
    shareStep3Title: "시간대",
    shareStep3Helper: "놀이터가 가장 많이 사용되는 시간을 이해하는 데 도움이 됩니다.",
    morning: "오전",
    afternoon: "오후",
    evening: "저녁",
    finish: "완료",
    shareStep4Title: "감사합니다",
    shareStep4Text: "귀하의 의견이 예술가의 디자인 형성에 도움이 될 것입니다.",
    updatesLabel: "프로젝트 업데이트 받기",
    emailPlaceholder: "your@email.com (선택사항)",
    emailMeta: "디자인 진행 상황에 대한 이메일 총 3-4개. 스팸 없음.",
    done: "완료",
    
    // Vote flow
    voteStep1Label: "귀하의 우선순위",
    voteStep1Title: "예술가가 무엇을 우선시해야 할까요?",
    voteInstructions: "귀하에게 중요한 것을 두 개 이상 선택하세요.",
    voteOptionShade: "더운 날을 위한 더 많은 그늘",
    voteOptionSeating: "좌석 (보호자 및 조부모를 위한)",
    voteOptionAges: "다양한 연령대가 함께 즐길 수 있는 놀이",
    voteOptionCultures: "우리 문화와 연결된 느낌의 공간",
    voteOptionMovement: "창의적인 움직임 (표준 장비만이 아닌)",
    voteOptionGathering: "모이는 장소, 단순히 놀기만 하는 곳이 아닌",
    voteOptionOther: "기타",
    voteOtherPlaceholder: "무엇인지 알려주세요...",
    submitBtn: "제출",
    voteStep2Title: "귀하의 의견이 집계되었습니다",
    voteStep2Text: "예술가는 이러한 우선순위를 사용하여 디자인을 안내할 것입니다.",
    seeReferencesBtn: "디자인 참고자료 보기 →",
    shareActionLabel: "놀이터를 어떻게 사용하는지 공유하시겠습니까?",
    shareActionBtn: "사진 공유",
    
    // Alerts
    alertDescription: "계속하기 전에 설명을 추가하세요.",
    alertVote: "최소 두 개의 옵션을 선택하세요.",
    alertVoteOtherEmpty: "'기타'가 무엇을 의미하는지 설명해주세요."
  },
  
  ar: {
    // Landing page
    kicker: "Woodside Play Lab",
    headline: "كيف تستخدم هذه الساحة؟",
    intro: "نحن نعيد تصميم ساحة General Hart بمساهمة المجتمع الذي يستخدمها فعلياً.",
    aboutLabel: "حول هذا المشروع",
    aboutText: "STREETOYSTER QUEENS تكلف فناناً بإعادة تصور هذه الساحة بناءً على كيفية استخدامك لها.",
    aboutMeta: "Alex Tudela، من سكان Woodside\nمتقدم لجائزة David 2026\nفي حوار مع NYC Parks ومجلس المجتمع 2",
    share: "مشاركة الصور",
    vote: "أخبرنا",
    timelineLabel: "ماذا سيحدث بعد ذلك",
    timelineSteps: "→ صيف 2026: يراجع الفنان مدخلات المجتمع\n→ خريف 2026: مشاركة مفاهيم التصميم مع المجتمع\n→ شتاء 2026: الموافقة على التصميم النهائي\n→ ربيع 2027: يبدأ التركيب",
    followText: "تابع العملية:",
    meta: "مفتوح للجميع · أي لغة · لا يلزم حساب",
    inspirationPrompt: "هل تريد أن ترى كيف يتم إعادة تصور ساحات اللعب الأخرى حول العالم؟",
    inspirationPromptVote: "هل تريد أن ترى ما هو ممكن لهذا المكان؟",
    designReferenceBtn: "استكشف مراجع التصميم →",
    
    // Share flow
    shareStep1Label: "مشاركة صورة",
    shareStep1Title: "أرنا كيف تستخدم هذا المكان",
    shareStep1Helper: "اللعب، الراحة، التجمع، الانتظار، المرور—كل شيء مهم.",
    uploadPhoto: "التقاط صورة",
    skipStep: "تخطي هذه الخطوة",
    privacyNote: "الخصوصية محمية: يمكن طمس الوجوه، تستخدم الصور فقط لتخطيط التصميم ولن يتم نشرها علناً.",
    shareStep2Label: "أخبرنا المزيد (اختياري)",
    shareStep2Title: "ماذا يحدث؟",
    shareStep2Helper: "جملة أو جملتان مثالية. اكتب بأي لغة.",
    textareaPlaceholder: "أطفالي ينتظرون هنا بعد المدرسة لأن هناك ظل.",
    continueBtn: "متابعة",
    shareStep3Label: "متى تستخدم هذه الحديقة؟",
    shareStep3Title: "وقت اليوم",
    shareStep3Helper: "يساعدنا على فهم متى يتم استخدام الساحة أكثر.",
    morning: "صباحاً",
    afternoon: "بعد الظهر",
    evening: "مساءً",
    finish: "إنهاء",
    shareStep4Title: "شكراً لك",
    shareStep4Text: "ستساعد مدخلاتك في تشكيل تصميم الفنان.",
    updatesLabel: "احصل على تحديثات المشروع",
    emailPlaceholder: "your@email.com (اختياري)",
    emailMeta: "إجمالي 3-4 رسائل بريد إلكتروني حول تقدم التصميم. بدون إزعاج.",
    done: "تم",
    
    // Vote flow
    voteStep1Label: "أولوياتك",
    voteStep1Title: "ما الذي يجب أن يعطيه الفنان الأولوية؟",
    voteInstructions: "اختر شيئين أو أكثر مما يهمك.",
    voteOptionShade: "المزيد من الظل للأيام الحارة",
    voteOptionSeating: "مقاعد (لمقدمي الرعاية والأجداد)",
    voteOptionAges: "لعب يعمل لمختلف الأعمار معاً",
    voteOptionCultures: "مساحات تشعر بالارتباط بثقافاتنا",
    voteOptionMovement: "حركة إبداعية (ليس فقط المعدات القياسية)",
    voteOptionGathering: "أماكن للتجمع، وليس فقط اللعب",
    voteOptionOther: "أخرى",
    voteOtherPlaceholder: "أخبرنا ماذا...",
    submitBtn: "إرسال",
    voteStep2Title: "تم احتساب مدخلاتك",
    voteStep2Text: "سيستخدم الفنان هذه الأولويات لتوجيه التصميم.",
    seeReferencesBtn: "شاهد مراجع التصميم →",
    shareActionLabel: "هل تريد مشاركة كيفية استخدامك للساحة؟",
    shareActionBtn: "مشاركة صورة",
    
    // Alerts
    alertDescription: "يرجى إضافة وصف قبل المتابعة.",
    alertVote: "يرجى تحديد خيارين على الأقل.",
    alertVoteOtherEmpty: "يرجى وصف ما تعنيه 'أخرى' بالنسبة لك."
  }
};
